name: nilaway
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  nilaway:
    name: nilaway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0 https://github.com/actions/checkout/releases/tag/v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0 https://github.com/actions/setup-go/releases/tag/v6.5.0
        with:
          go-version: 1.26.x
          cache: false
      - name: install nilaway
        run: GOTOOLCHAIN=local go install go.uber.org/nilaway/cmd/nilaway@v0.0.0-20260515015210-fd187751154f
      - name: run nilaway
        run: nilaway -include-pkgs=github.com/blinklabs-io/dmq-lib ./...
